//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaCoHealth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmaCoHealth_25Entities : DbContext
    {
        public PharmaCoHealth_25Entities()
            : base("name=PharmaCoHealth_25Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<BloodBank> BloodBanks { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PATIENTINFO> PATIENTINFOes { get; set; }
        public virtual DbSet<PATIENTREPORT> PATIENTREPORTs { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Specialize> Specializes { get; set; }
    }
}
